[package]
name = "layer2_forwarder"
version = "0.1.0"
authors = ["Elliot Levin <elliot.levin@cheproximity.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
