on: [push]

name: Build - Windows

jobs:
  build:
    name: Build - Windows
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install WinPcap
        run: |
          choco install winpcap
          curl https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -o dev_winpcap.zip
          unzip dev_winpcap.zip
          cp -rv WpdPack/Lib/x64/* /c/Rust/.rustup/toolchains/stable-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/lib/
        shell: bash
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: layer2-forwarder-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/chainnet-central-router.exe
            target/${{ matrix.target }}/release/chainnet-node-router.exe

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Deploy to S3
        run: |
          aws s3 cp --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE target/${{ matrix.target }}/release/chainnet-central-router.exe s3://chainnet/central-router-${{ matrix.target }}.exe \
          && aws s3 cp --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE target/${{ matrix.target }}/release/chainnet-node-router.exe s3://chainnet/node-router-${{ matrix.target }}.exe
        shell: bash
    