on: [push]

name: Build

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    name: Build
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            platform: ubuntu-latest
          - target: x86_64-apple-darwin
            platform: macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: layer2-forwarder-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/chainnet-central-router
            target/${{ matrix.target }}/release/chainnet-node-router

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Deploy to S3
        run: |
          aws s3 cp --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE target/${{ matrix.target }}/release/chainnet-central-router s3://chainnet/central-router-${{ matrix.target }} \
          && aws s3 cp --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE target/${{ matrix.target }}/release/chainnet-node-router s3://chainnet/node-router-${{ matrix.target }} 
    